#!/usr/bin/env bash
# Non-mutating repository-preflight regression tests with a minimal PATH.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
case "$(uname -s):$(uname -m)" in
  Linux:x86_64) fixture_platform=x86_64-unknown-linux-musl ;;
  Linux:aarch64|Linux:arm64) fixture_platform=aarch64-unknown-linux-musl ;;
  Darwin:arm64) fixture_platform=aarch64-apple-darwin ;;
  *) echo "unsupported fixture platform" >&2; exit 1 ;;
esac
tmp="$(mktemp -d)"
cleanup() {
  rm -rf "$tmp"
}
trap cleanup EXIT

mkdir -p "$tmp/bin" "$tmp/home" "$tmp/work/release" "$tmp/work/scripts"
cp "$repo_root/release/taskfleet-release.json" "$tmp/work/release/"
cp "$repo_root/scripts/validate-release-topology.sh" "$tmp/work/scripts/"
for tool in bash grep jq sed dirname base64 cp awk uname shasum tar xz cmp mktemp rm; do
  tool_path="$(command -v "$tool")" || {
    echo "test prerequisite missing: $tool" >&2
    exit 1
  }
  ln -s "$tool_path" "$tmp/bin/$tool"
done

cat >"$tmp/bin/git" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >>"$GIT_STUB_LOG"
case "$*" in
  "rev-parse --show-toplevel")
    printf '%s\n' "$GIT_STUB_ROOT"
    ;;
  "remote get-url origin"|"remote get-url --push --all origin")
    printf '%s\n' "$GIT_STUB_ORIGIN"
    ;;
  *)
    echo "stub git: unexpected arguments: $*" >&2
    exit 96
    ;;
esac
STUB
chmod +x "$tmp/bin/git"

cat >"$tmp/bin/gh" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >>"$GH_STUB_LOG"

# repo view accepts the repository as its documented positional argument. Reject
# its unsupported forms explicitly without condemning valid `gh run -R` calls.
if [[ "${1:-}" == repo && "${2:-}" == view ]]; then
  for arg in "$@"; do
    case "$arg" in
      -R|-R*|--repo|--repo=*)
        echo "stub gh: repo view repository flags are unsupported" >&2
        exit 97
        ;;
    esac
  done
fi

if [[ "$*" == 'api repos/jarimustonen/homebrew-shipshape/contents/Formula/shipshape.rb' ]]; then
  if [[ "${FORMULA_FAIL:-0}" == 1 ]]; then exit 97; fi
  if [[ "${FORMULA_MALFORMED:-0}" == 1 ]]; then echo '{"bad":true}'; exit 0; fi
  printf '# Generated by shipshape;\nclass Shipshape < Formula\n  version "%s"\n    url "https://github.com/jarimustonen/ossctl/releases/download/v%s/shipshape-%s.tar.xz"\n    sha256 "%s"\nend\n' "${FORMULA_VERSION:-0.12.4}" "${FORMULA_VERSION:-0.12.4}" "$FIXTURE_PLATFORM" "$FIXTURE_SHA" | base64 | jq -Rs '{type:"file",path:"Formula/shipshape.rb",encoding:"base64",sha:"0000000000000000000000000000000000000000",content:.}'
  exit 0
fi
if [[ "$*" == "api repos/jarimustonen/ossctl/releases/tags/v${FORMULA_VERSION:-0.12.4}" ]]; then
  jq -n --arg tag "v${FORMULA_VERSION:-0.12.4}" --arg archive "shipshape-$FIXTURE_PLATFORM.tar.xz" --arg digest "sha256:${RELEASE_SHA:-$FIXTURE_SHA}" '{tag_name:$tag,draft:false,prerelease:false,assets:[{name:$archive,digest:$digest}]}'
  exit 0
fi
if [[ "$*" == "api repos/jarimustonen/ossctl/git/ref/tags/v${FORMULA_VERSION:-0.12.4}" ]]; then
  jq -n --arg ref "refs/tags/v${FORMULA_VERSION:-0.12.4}" '{ref:$ref,object:{type:"tag",sha:"1111111111111111111111111111111111111111"}}'
  exit 0
fi
if [[ "$*" == 'api repos/jarimustonen/ossctl/git/tags/1111111111111111111111111111111111111111' ]]; then
  jq -n --arg sha "${SOURCE_COMMIT:-8db733bd70f566ab39b4cd774901c6e2ca8fd2c3}" '{object:{type:"commit",sha:$sha}}'
  exit 0
fi
if [[ "$1" == release && "$2" == download ]]; then
  [[ "$*" == "release download v${FORMULA_VERSION:-0.12.4} -R jarimustonen/ossctl --pattern shipshape-$FIXTURE_PLATFORM.tar.xz -D "* ]] || exit 98
  cp "$FIXTURE_ARCHIVE" "${!#}/shipshape-$FIXTURE_PLATFORM.tar.xz"
  exit 0
fi
if [[ $# -eq 7 && "$1" == repo && "$2" == view &&
      "$3" == "${GH_STUB_VIEW_EXPECTED:-jarimustonen/taskfleet}" && "$4" == --json &&
      "$5" == nameWithOwner && "$6" == -q && "$7" == .nameWithOwner ]]; then
  printf '%s\n' "$GH_STUB_REPO"
  exit 0
fi

echo "stub gh: unexpected arguments: $*" >&2
exit 98
STUB
chmod +x "$tmp/bin/gh"

cat >"$tmp/bin/shipshape" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >>"$SHIPSHAPE_STUB_LOG"
if [[ "$*" == "version --json" ]]; then
  if [[ "${INCOMPATIBLE_PROTOCOL:-0}" == 1 ]]; then echo '{"schema_version":2,"data":{}}'; exit 0; fi
  if [[ "${SHIPSHAPE_STUB_OMIT_COMMIT:-0}" == 1 ]]; then
    jq -n --arg version "${SHIPSHAPE_STUB_VERSION:-0.12.4}" \
      '{schema_version:1,data:{version:$version,schema_version:1}}'
  else
    jq -n --arg version "${SHIPSHAPE_STUB_VERSION:-0.12.4}" --arg commit "${SHIPSHAPE_STUB_COMMIT:-8db733bd70f566ab39b4cd774901c6e2ca8fd2c3}" \
      '{schema_version:1,data:{version:$version,commit:$commit,schema_version:1,supported_schemas:[1]}}'
  fi
  exit 0
fi
if [[ "${1:-}" == release && "${2:-}" == show ]]; then
  # Sentinel: reaching this point proves repository preflight passed. Stop before
  # any release state, Git refs, or remote operations can be touched.
  exit 42
fi
echo "stub shipshape: unexpected arguments: $*" >&2
exit 99
STUB
chmod +x "$tmp/bin/shipshape"

mkdir -p "$tmp/archive/shipshape-${fixture_platform}"
cp "$tmp/bin/shipshape" "$tmp/archive/shipshape-${fixture_platform}/shipshape"
tar -cJf "$tmp/release.tar.xz" -C "$tmp/archive" "shipshape-${fixture_platform}"
fixture_sha="$(shasum -a 256 "$tmp/release.tar.xz" | awk '{print $1}')"

readonly test_run_id="01M0JA657EJJJYC7J7230JF42N"

run_wrapper() {
  local gh_repo="${1:-jarimustonen/taskfleet}"
  local origin="${2:-git@github.com:jarimustonen/taskfleet.git}"
  local view_expected="${3:-jarimustonen/taskfleet}"
  local candidate_run="${4:-$test_run_id}"
  env -i \
    HOME="$tmp/home" \
    PATH="$tmp/bin" \
    GH_STUB_LOG="$tmp/gh.log" \
    GIT_STUB_LOG="$tmp/git.log" \
    GIT_STUB_ROOT="$tmp/work" \
    GIT_STUB_ORIGIN="$origin" \
    SHIPSHAPE_STUB_LOG="$tmp/shipshape.log" \
    SHIPSHAPE_STUB_VERSION="${SHIPSHAPE_STUB_VERSION:-0.12.4}" \
    SHIPSHAPE_STUB_COMMIT="${SHIPSHAPE_STUB_COMMIT:-8db733bd70f566ab39b4cd774901c6e2ca8fd2c3}" \
    SHIPSHAPE_STUB_OMIT_COMMIT="${SHIPSHAPE_STUB_OMIT_COMMIT:-0}" \
    FIXTURE_ARCHIVE="$tmp/release.tar.xz" FIXTURE_SHA="$fixture_sha" FIXTURE_PLATFORM="$fixture_platform" \
    RELEASE_SHA="${RELEASE_SHA:-}" SOURCE_COMMIT="${SOURCE_COMMIT:-}" FORMULA_MALFORMED="${FORMULA_MALFORMED:-0}" INCOMPATIBLE_PROTOCOL="${INCOMPATIBLE_PROTOCOL:-0}" \
    FORMULA_VERSION="${FORMULA_VERSION:-0.12.4}" FORMULA_FAIL="${FORMULA_FAIL:-0}" \
    GH_STUB_REPO="$gh_repo" \
    GH_STUB_VIEW_EXPECTED="$view_expected" \
    "$repo_root/scripts/shipshape-release.sh" resume "$candidate_run" \
    >"$tmp/stdout" 2>"$tmp/stderr"
}

reset_logs() {
  : >"$tmp/gh.log"
  : >"$tmp/git.log"
  : >"$tmp/shipshape.log"
}

assert_no_release_show() {
  if grep -F 'release show' "$tmp/shipshape.log" >/dev/null; then
    echo "failed preflight reached release show" >&2; exit 1
  fi
}

# Reject hostile or malformed identifiers before repository/network inspection;
# quoting is not a substitute for enforcing the one documented input grammar.
for malformed in lowercase01m0ja657ejjjyc7j7230jf42n '../run' '--help' '01M0JA657EJJJYC7J7230JF42N;touch'; do
  reset_logs
  set +e
  run_wrapper jarimustonen/taskfleet git@github.com:jarimustonen/taskfleet.git jarimustonen/taskfleet "$malformed"
  status=$?
  set -e
  [[ "$status" -eq 2 ]] || { echo "malformed run id was not rejected: $malformed" >&2; exit 1; }
  test ! -s "$tmp/gh.log" || { echo "malformed run id reached gh: $malformed" >&2; exit 1; }
  grep -F "invalid release run id: $malformed" "$tmp/stderr" >/dev/null
  ! grep -F 'release show' "$tmp/shipshape.log" >/dev/null || { echo "malformed run id reached release show" >&2; exit 1; }
done

reset_logs
set +e
run_wrapper
status=$?
set -e
[[ "$status" -eq 42 ]] || {
  echo "supported gh repo view invocation did not pass preflight (status=$status)" >&2
  cat "$tmp/stderr" >&2
  exit 1
}
grep -Fx "release show $test_run_id --json" "$tmp/shipshape.log" >/dev/null || {
  echo "successful repository preflight did not reach release show sentinel" >&2
  cat "$tmp/shipshape.log" >&2
  exit 1
}

# Repository identity is read from the admitted topology rather than duplicated
# in the wrapper. Prove an isolated future-R9 coordinate flows to git and gh.
jq '.repository = "jarimustonen/taskfleet"' "$tmp/work/release/taskfleet-release.json" >"$tmp/topology.json"
mv "$tmp/topology.json" "$tmp/work/release/taskfleet-release.json"
reset_logs
set +e
run_wrapper jarimustonen/taskfleet git@github.com:jarimustonen/taskfleet.git jarimustonen/taskfleet
status=$?
set -e
[[ "$status" -eq 42 ]] || { echo "data-driven repository coordinate was rejected" >&2; cat "$tmp/stderr" >&2; exit 1; }
grep -Fx 'repo view jarimustonen/taskfleet --json nameWithOwner -q .nameWithOwner' "$tmp/gh.log" >/dev/null
cp "$repo_root/release/taskfleet-release.json" "$tmp/work/release/"

reset_logs
set +e
run_wrapper unrelated-owner/unrelated-repo
status=$?
set -e
[[ "$status" -eq 1 ]] || {
  echo "GitHub repository mismatch did not fail closed (status=$status)" >&2
  cat "$tmp/stderr" >&2
  exit 1
}
grep -Fx 'release repository mismatch: origin=jarimustonen/taskfleet push=jarimustonen/taskfleet gh=unrelated-owner/unrelated-repo expected=jarimustonen/taskfleet' "$tmp/stderr" >/dev/null || {
  echo "GitHub repository mismatch did not emit the expected diagnostic" >&2
  cat "$tmp/stderr" >&2
  exit 1
}
assert_no_release_show

reset_logs
set +e
run_wrapper jarimustonen/taskfleet https://github.com/unrelated-owner/unrelated-repo.git
status=$?
set -e
[[ "$status" -eq 1 ]] || {
  echo "origin repository mismatch did not fail closed (status=$status)" >&2
  cat "$tmp/stderr" >&2
  exit 1
}
grep -Fx 'release repository mismatch: origin=unrelated-owner/unrelated-repo push=unrelated-owner/unrelated-repo gh=jarimustonen/taskfleet expected=jarimustonen/taskfleet' "$tmp/stderr" >/dev/null || {
  echo "origin repository mismatch did not emit the expected diagnostic" >&2
  cat "$tmp/stderr" >&2
  exit 1
}
assert_no_release_show

# Versions are not allowlisted: both prior and future stable versions pass when
# the published metadata, bytes, and source agree.
for version in 0.12.3 0.12.4 0.12.9 0.13.0; do
  reset_logs
  set +e
  SHIPSHAPE_STUB_VERSION="$version" FORMULA_VERSION="$version" run_wrapper
  status=$?
  set -e
  [[ "$status" -eq 42 ]] || { echo "compatible stable $version rejected" >&2; cat "$tmp/stderr" >&2; exit 1; }
done
for failure in mismatch bad_commit missing_commit offline malformed bad_digest bad_source incompatible forged; do
  reset_logs
  set +e
  case "$failure" in
    mismatch) SHIPSHAPE_STUB_VERSION=0.12.3 run_wrapper ;;
    bad_commit) SHIPSHAPE_STUB_COMMIT=0000000000000000000000000000000000000000 run_wrapper ;;
    missing_commit) SHIPSHAPE_STUB_OMIT_COMMIT=1 run_wrapper ;;
    offline) FORMULA_FAIL=1 run_wrapper ;;
    malformed) FORMULA_MALFORMED=1 run_wrapper ;;
    bad_digest) RELEASE_SHA=0000000000000000000000000000000000000000000000000000000000000000 run_wrapper ;;
    bad_source) SOURCE_COMMIT=0000000000000000000000000000000000000000 run_wrapper ;;
    incompatible) INCOMPATIBLE_PROTOCOL=1 run_wrapper ;;
    forged) printf '\n# forged executable\n' >>"$tmp/bin/shipshape"; run_wrapper ;;
  esac
  status=$?
  set -e
  [[ "$status" -ne 0 && "$status" -ne 42 ]] || { echo "$failure admitted" >&2; exit 1; }
  assert_no_release_show
  if [[ "$failure" == forged ]]; then cp "$tmp/archive/shipshape-${fixture_platform}/shipshape" "$tmp/bin/shipshape"; fi
done

for abandoned in 01M0FD8FSTMGYG8YTV92WMWC87 01M0FG88NAKBJ7Y3QNFZEHRM4K; do
  reset_logs
  set +e
  env -i HOME="$tmp/home" PATH="$tmp/bin" GH_STUB_LOG="$tmp/gh.log" GIT_STUB_LOG="$tmp/git.log" \
    GIT_STUB_ROOT="$tmp/work" GIT_STUB_ORIGIN=git@github.com:jarimustonen/taskfleet.git \
    SHIPSHAPE_STUB_LOG="$tmp/shipshape.log" SHIPSHAPE_STUB_VERSION=0.12.4 \
    FIXTURE_ARCHIVE="$tmp/release.tar.xz" FIXTURE_SHA="$fixture_sha" FIXTURE_PLATFORM="$fixture_platform" \
    SHIPSHAPE_STUB_COMMIT=8db733bd70f566ab39b4cd774901c6e2ca8fd2c3 \
    FORMULA_VERSION=0.12.4 GH_STUB_REPO=jarimustonen/taskfleet "$repo_root/scripts/shipshape-release.sh" resume "$abandoned" \
    >"$tmp/stdout" 2>"$tmp/stderr"
  status=$?
  set -e
  [[ "$status" -eq 2 ]] || { echo "abandoned run $abandoned was not blocked (status=$status)" >&2; exit 1; }
  grep -F "release run $abandoned is permanently abandoned and must never be resumed" "$tmp/stderr" >/dev/null
  ! grep -F "release show" "$tmp/shipshape.log" >/dev/null || { echo "abandoned run $abandoned reached release show" >&2; exit 1; }
done

set +e
env -i PATH="$tmp/bin" GH_STUB_LOG="$tmp/gh.log" GH_STUB_REPO=unused \
  "$tmp/bin/gh" repo view -R jarimustonen/taskfleet \
  --json nameWithOwner -q .nameWithOwner >/dev/null 2>&1
status=$?
set -e
[[ "$status" -eq 97 ]] || {
  echo "gh fixture did not explicitly reject the old repo view -R form (status=$status)" >&2
  exit 1
}

# R10 activation is now structurally ready. The exact 0.12.3 protocol fixture
# owns the cut-path proof; this preflight suite must no longer assert the retired
# blocked ledger state.
"$repo_root/scripts/verify-release-activation.sh" >/dev/null

"$repo_root/scripts/test-shipshape-release-held-tag.sh"
echo "release wrapper tests passed"
